sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
minio:
    access-key: minioadmin
    secret-key: minioadmin
    endpoint: http://127.0.0.1:9000
    bucket: sky
